[2024-04-29T18:46:00.843+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T18:46:00.880+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_model_1.train scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T18:46:00.893+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_model_1.train scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T18:46:00.894+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T18:46:00.909+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): train> on 2024-04-28 00:00:00+00:00
[2024-04-29T18:46:00.929+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train_model_1', 'train', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dag_train.py', '--cfg-path', '/tmp/tmp0irdo74c']
[2024-04-29T18:46:00.932+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=428) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T18:46:00.933+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask train
[2024-04-29T18:46:00.933+0000] {standard_task_runner.py:63} INFO - Started process 466 to run task
[2024-04-29T18:46:00.995+0000] {task_command.py:426} INFO - Running <TaskInstance: train_model_1.train scheduled__2024-04-28T00:00:00+00:00 [running]> on host d1f0cdf1c56a
[2024-04-29T18:46:01.103+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='train_model_1' AIRFLOW_CTX_TASK_ID='train' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T18:46:01.105+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T18:46:01.204+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_train.py:46 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T18:46:02.242+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T18:46:02.243+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_train.py", line 74, in train_model
    VALUES {tuple(model_name, params, metrics)}
                  ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'model_name' where it is not associated with a value
[2024-04-29T18:46:02.265+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=train_model_1, task_id=train, execution_date=20240428T000000, start_date=20240429T184600, end_date=20240429T184602
[2024-04-29T18:46:02.282+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 7 for task train (cannot access local variable 'model_name' where it is not associated with a value; 466)
[2024-04-29T18:46:02.317+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-29T18:46:02.345+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T18:46:02.349+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
