[2024-04-29T17:04:50.305+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-29T17:04:50.424+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fill_data_v10.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T17:04:50.431+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fill_data_v10.processed scheduled__2024-04-28T00:00:00+00:00 [queued]>
[2024-04-29T17:04:50.433+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 6
[2024-04-29T17:04:50.445+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): processed> on 2024-04-28 00:00:00+00:00
[2024-04-29T17:04:50.451+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'fill_data_v10', 'processed', 'scheduled__2024-04-28T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dag_raw_processed.py', '--cfg-path', '/tmp/tmpivo7yd6c']
[2024-04-29T17:04:50.453+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=886) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-29T17:04:50.454+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask processed
[2024-04-29T17:04:50.455+0000] {standard_task_runner.py:63} INFO - Started process 888 to run task
[2024-04-29T17:04:50.491+0000] {task_command.py:426} INFO - Running <TaskInstance: fill_data_v10.processed scheduled__2024-04-28T00:00:00+00:00 [running]> on host 15fcc90b2790
[2024-04-29T17:04:50.549+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mosula' AIRFLOW_CTX_DAG_ID='fill_data_v10' AIRFLOW_CTX_TASK_ID='processed' AIRFLOW_CTX_EXECUTION_DATE='2024-04-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-28T00:00:00+00:00'
[2024-04-29T17:04:50.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-29T17:04:50.575+0000] {logging_mixin.py:188} WARNING - /opt/***/dags/dag_raw_processed.py:45 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2024-04-29T17:05:00.233+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-04-29T17:05:00.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-29T17:05:00.241+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=fill_data_v10, task_id=processed, execution_date=20240428T000000, start_date=20240429T170450, end_date=20240429T170500
[2024-04-29T17:05:00.295+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-29T17:05:00.311+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-29T17:05:00.316+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
